// @vitest-environment jsdom
import React from "react"
import { afterEach, expect, it, vi } from "vitest"
import { cleanup, fireEvent, render, screen } from "@testing-library/react"
const server = vi.hoisted(() => ({ list: vi.fn(), directory: vi.fn() }))
vi.mock("@/lib/actions/artists", () => ({ listArtists: server.list }))
vi.mock("@/lib/actions/artist-directory", () => ({ listArtistDirectory: server.directory }))
import ArtistsPage from "@/app/dashboard/artists/page"
afterEach(cleanup)
it("does not render an empty roster when the dedicated read fails", async () => {
  server.directory.mockRejectedValueOnce(new Error("directory incomplete"))
  await expect(ArtistsPage()).rejects.toThrow("directory incomplete")
})
it("keeps every searchable genre visible in its artist row", async () => {
  server.directory.mockResolvedValue([{ ...artist("a", "Aurora"), genres: ["House", "Techno", "Jazz", "Ambient"] }])
  render(await ArtistsPage())
  expect(screen.getByText("House / Techno / Jazz / Ambient")).toBeTruthy()
})
it("passes only the dedicated directory read to the client", async () => {
  const entry = artist("directory", "Directory Act")
  server.directory.mockResolvedValue([entry])
  server.list.mockResolvedValue([{ ...artist("legacy", "Legacy Act"), email: "private", allergies: "private" }])
  const page = await ArtistsPage()
  expect(page.props.artists).toEqual([entry])
  expect(Object.keys(page.props.artists[0]).sort()).toEqual(["id", "name", "surname", "stage_name", "genres", "location", "fee", "currency"].sort())
})
it("provides a keyboard-focusable named table scroll region", async () => {
  server.directory.mockResolvedValue([artist("a", "Aurora")])
  render(await ArtistsPage())
  const region = screen.getByRole("region", { name: "Artists table" })
  expect(region.tabIndex).toBe(0)
  expect(region.contains(screen.getByRole("table"))).toBe(true)
})
it("distinguishes zero and missing fees without inventing currency", async () => {
  server.directory.mockResolvedValue([{ ...artist("a", "Aurora"), fee: 0, currency: "EUR" }, { ...artist("b", "Borealis"), fee: 1250 }, artist("c", "Comet")])
  render(await ArtistsPage())
  expect(screen.getByText("EUR 0")).toBeTruthy()
  expect(screen.getByText("1,250 (currency unavailable)")).toBeTruthy()
  expect(screen.getByText("Not provided")).toBeTruthy()
  expect(screen.queryByText(/\$1,250/)).toBeNull()
})
it("reports event counts as unavailable, never zero", async () => {
  server.directory.mockResolvedValue([artist("a", "Aurora")])
  render(await ArtistsPage())
  expect(screen.getByText("Unavailable")).toBeTruthy()
  expect(screen.queryByText("0")).toBeNull()
})
it("opens an artist-specific keyboard menu with real routes and disabled deletion", async () => {
  server.directory.mockResolvedValue([artist("a", "Aurora")])
  render(await ArtistsPage())
  const trigger = screen.getByRole("button", { name: "Actions for Aurora" })
  trigger.focus()
  fireEvent.keyDown(trigger, { key: "ArrowDown" })
  expect(await screen.findByRole("menuitem", { name: "Edit" })).toHaveProperty("href", "http://localhost:3000/dashboard/artists/a/edit")
  expect(screen.getByRole("menuitem", { name: "View details" }).getAttribute("href")).toBe("/dashboard/artists/a")
  expect(screen.getByRole("menuitem", { name: "Delete (unavailable)" }).getAttribute("aria-disabled")).toBe("true")
})
it("keeps export explicitly unavailable", async () => {
  server.directory.mockResolvedValue([artist("a", "Aurora")])
  render(await ArtistsPage())
  expect((screen.getByRole("button", { name: /Download CSV/ }) as HTMLButtonElement).disabled).toBe(true)
})
it("distinguishes no matches from an empty roster", async () => {
  server.directory.mockResolvedValue([artist("a", "Aurora")])
  render(await ArtistsPage())
  fireEvent.change(screen.getByRole("searchbox", { name: "Search artists" }), { target: { value: "missing" } })
  expect(screen.getByText("No artists match your search.")).toBeTruthy()
  expect(screen.queryByText("No artists yet. Add your first artist to get started.")).toBeNull()
  expect(screen.getByText("Showing 0-0 of 0 artists")).toBeTruthy()
})
it("labels search and clearing restores all rows, page one and input focus", async () => {
  server.directory.mockResolvedValue(Array.from({ length: 41 }, (_, i) => artist(String(i), `Artist ${String(i).padStart(2, "0")}`)))
  render(await ArtistsPage())
  const input = screen.getByRole("searchbox", { name: "Search artists" })
  fireEvent.change(input, { target: { value: "Artist" } })
  fireEvent.click(screen.getByRole("button", { name: "Next" }))
  fireEvent.click(screen.getByRole("button", { name: "Clear search" }))
  expect((input as HTMLInputElement).value).toBe("")
  expect(document.activeElement).toBe(input)
  expect(screen.getByText("Showing 1-20 of 41 artists")).toBeTruthy()
})
it("clamps the current page when refreshed data shrinks", async () => {
  const rows = Array.from({ length: 41 }, (_, i) => artist(String(i), `Artist ${String(i).padStart(2, "0")}`))
  server.directory.mockResolvedValue(rows)
  const view = render(await ArtistsPage())
  fireEvent.click(screen.getByRole("button", { name: "Next" }))
  fireEvent.click(screen.getByRole("button", { name: "Next" }))
  server.directory.mockResolvedValue(rows.slice(0, 21))
  view.rerender(await ArtistsPage())
  expect(screen.getByText("Showing 21-21 of 21 artists")).toBeTruthy()
  expect(screen.getByText("Artist 20")).toBeTruthy()
})
it("search resets the current page and reports filtered ranges", async () => {
  server.directory.mockResolvedValue(Array.from({ length: 41 }, (_, i) => artist(String(i), `Artist ${String(i).padStart(2, "0")}`)))
  render(await ArtistsPage())
  fireEvent.click(screen.getByRole("button", { name: "Next" }))
  fireEvent.change(screen.getByPlaceholderText("Search by name, genre or location"), { target: { value: "Artist 40" } })
  expect(screen.getByText("Artist 40")).toBeTruthy()
  expect(screen.getByText("Showing 1-1 of 1 artists")).toBeTruthy()
})
it("keeps unavailable pagination boundaries focusable and guards their actions", async () => {
  server.directory.mockResolvedValue(Array.from({ length: 21 }, (_, i) => artist(String(i), `Artist ${String(i).padStart(2, "0")}`)))
  render(await ArtistsPage())
  const previous = screen.getByRole("button", { name: "Previous" }) as HTMLButtonElement
  const next = screen.getByRole("button", { name: "Next" }) as HTMLButtonElement
  expect(previous.getAttribute("aria-disabled")).toBe("true")
  expect(previous.disabled).toBe(false)
  fireEvent.click(previous)
  expect(screen.getByText("Showing 1-20 of 21 artists")).toBeTruthy()
  next.focus()
  fireEvent.click(next)
  expect(next.getAttribute("aria-disabled")).toBe("true")
  expect(next.disabled).toBe(false)
  expect(document.activeElement).toBe(next)
  fireEvent.click(next)
  expect(screen.getByText("Showing 21-21 of 21 artists")).toBeTruthy()
})

it("renders only twenty rows and moves to the genuine final page", async () => {
  server.directory.mockResolvedValue(Array.from({ length: 21 }, (_, i) => artist(String(i), `Artist ${String(i).padStart(2, "0")}`)))
  render(await ArtistsPage())
  expect(screen.getAllByRole("row")).toHaveLength(21)
  expect(screen.queryByText("Artist 20")).toBeNull()
  const next = screen.getByRole("button", { name: "Next" })
  next.focus()
  fireEvent.click(next)
  expect(screen.getAllByRole("row")).toHaveLength(2)
  expect(screen.getByText("Artist 20")).toBeTruthy()
  expect(screen.getByText("Showing 21-21 of 21 artists")).toBeTruthy()
  expect(document.activeElement).toBe(next)
  expect(next.getAttribute("aria-disabled")).toBe("true")
  fireEvent.click(screen.getByRole("button", { name: "Previous" }))
  expect(screen.getByText("Showing 1-20 of 21 artists")).toBeTruthy()
})
it("orders displayed names deterministically, not input or legal-name order", async () => {
  server.directory.mockResolvedValue([artist("z", "Zulu"), artist("b", "alpha"), artist("d", "Alpha"), artist("c", "Alpha"), { ...artist("u", "   "), name: "Bravo" }, artist("x", "")])
  render(await ArtistsPage())
  const links = screen.getAllByRole("link").filter((link) => link.className === "flex flex-col")
  expect(links.map((link) => link.getAttribute("href"))).toEqual(["c", "d", "b", "u", "x", "z"].map((id) => `/dashboard/artists/${id}`))
  expect(screen.getByText("Unknown")).toBeTruthy()
})

it.each(["  auROra  ", "Mila Gray", "ambient", "Rome", "[live]"])("search matches literal trimmed case-insensitive directory field %s", async (query) => {
  server.directory.mockResolvedValue([{ ...artist("a", "Aurora [live]"), name: "Mila", surname: "Gray", genres: ["House", "Techno", "Jazz", "Ambient"], location: "Rome" }, artist("b", "Borealis")])
  render(await ArtistsPage())
  fireEvent.change(screen.getByPlaceholderText("Search by name, genre or location"), { target: { value: query } })
  expect(screen.getByText("Aurora [live]")).toBeTruthy()
  expect(screen.queryByText("Borealis")).toBeNull()
})
const artist = (id: string, stage_name: string) => ({ id, stage_name, name: "", surname: null, genres: [], location: null, fee: null, currency: null })
it("search removes a nonmatching row on the actual Artists page", async () => {
  server.directory.mockResolvedValue([artist("a", "Aurora"), artist("b", "Borealis")])
  render(await ArtistsPage())
  expect(screen.getByText("Borealis")).toBeTruthy()
  fireEvent.change(screen.getByPlaceholderText("Search by name, genre or location"), { target: { value: "Aurora" } })
  expect(screen.queryByText("Borealis")).toBeNull()
  expect(screen.getByText("Aurora")).toBeTruthy()
})
